# Generated by Django 6.0.6 on 2026-06-25 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='full_name', max_length=200, null=True)),
                ('nombre_usuario', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('biografia', models.TextField(blank=True, db_column='bio', null=True)),
                ('url_avatar', models.TextField(blank=True, db_column='avatar_url', null=True)),
                ('telefono', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, db_column='address', null=True)),
                ('ciudad', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('pais', models.CharField(db_column='country', default='Colombia', max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('repartidor', 'Repartidor')], db_column='role', default='client', max_length=20)),
                ('esta_activo', models.BooleanField(db_column='is_active', default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'profiles',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField(db_column='message')),
                ('esta_leida', models.BooleanField(db_column='is_read', default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
    ]
