# Generated by Django 6.0.6 on 2026-06-26 00:22

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='name', max_length=100)),
                ('codigo', models.CharField(db_column='code', max_length=50, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permissions',
                'ordering': ['nombre'],
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='name', max_length=100)),
                ('codigo', models.CharField(db_column='code', max_length=50, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('permisos', models.ManyToManyField(db_table='role_permissions', related_name='roles', to='users.permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol_rbac',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.rol'),
        ),
    ]
