# Generated by Django 5.2.15 on 2026-06-26 00:39

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_populate_roles_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fecha_primer_login',
            field=models.DateTimeField(blank=True, db_column='first_login_at', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='password_cambiada',
            field=models.BooleanField(db_column='password_changed', default=True),
        ),
        migrations.CreateModel(
            name='InvitacionAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=150, unique=True)),
                ('nombre_completo', models.CharField(blank=True, db_column='full_name', max_length=200, null=True)),
                ('usuario_generado', models.CharField(db_column='generated_username', max_length=100, unique=True)),
                ('password_temporal_hash', models.CharField(db_column='temp_password_hash', max_length=255)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='sent_at')),
                ('fecha_expiracion', models.DateTimeField(db_column='expires_at')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('expirada', 'Expirada'), ('revocada', 'Revocada')], db_column='status', default='pendiente', max_length=20)),
                ('notas_internas', models.TextField(blank=True, db_column='internal_notes', null=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, db_column='accepted_at', null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, db_column='source_ip', null=True)),
                ('creado_por', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitaciones_creadas', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Invitación Administrador',
                'verbose_name_plural': 'Invitaciones Administrador',
                'db_table': 'admin_invitations',
                'ordering': ['-fecha_envio'],
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='invitacion',
            field=models.ForeignKey(blank=True, db_column='invitation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.invitacionadmin'),
        ),
    ]
