# Generated by Django 6.0.6 on 2026-06-25 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='status', default='Pendiente', max_length=50)),
                ('monto_total', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10)),
                ('direccion_envio', models.TextField(db_column='shipping_address')),
                ('cedula', models.CharField(blank=True, db_column='document_id', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='phone', max_length=30, null=True)),
                ('notas', models.TextField(blank=True, db_column='notes', null=True)),
                ('entregado_el', models.DateTimeField(blank=True, db_column='delivered_at', null=True)),
                ('notas_repartidor', models.TextField(blank=True, db_column='delivery_notes', null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('repartidor', models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='users.perfil')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='quantity')),
                ('precio_unitario', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('producto', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='products.producto')),
                ('pedido', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='interactions.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'order_items',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='rating', default=5)),
                ('comentario', models.TextField(db_column='content')),
                ('esta_aprobada', models.BooleanField(db_column='is_approved', default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('producto', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='products.producto')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'reviews',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='content')),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('reseña', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='interactions.reseña')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_interacciones', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'review_replies',
                'managed': getattr(settings, 'USE_SQLITE', False),
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('producto', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='products.producto')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorites',
                'managed': getattr(settings, 'USE_SQLITE', False),
                'unique_together': {('usuario', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('producto', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='products.producto')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='users.perfil')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'votes',
                'managed': getattr(settings, 'USE_SQLITE', False),
                'unique_together': {('usuario', 'producto')},
            },
        ),
    ]
