# Generated by Django 3.2.8 on 2026-04-06 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='rating', default=5)),
                ('comentario', models.TextField(db_column='content')),
                ('esta_aprobada', models.BooleanField(db_column='is_approved', default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='content')),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'review_replies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'votes',
                'managed': False,
            },
        ),
    ]
