# Generated by Django 3.2.8 on 2026-04-12 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='quantity')),
                ('precio_unitario', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(db_column='status', default='Pendiente', max_length=50)),
                ('monto_total', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10)),
                ('direccion_envio', models.TextField(db_column='shipping_address')),
                ('cedula', models.CharField(blank=True, db_column='document_id', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_column='phone', max_length=30, null=True)),
                ('notas', models.TextField(blank=True, db_column='notes', null=True)),
                ('entregado_el', models.DateTimeField(blank=True, db_column='delivered_at', null=True)),
                ('notas_repartidor', models.TextField(blank=True, db_column='delivery_notes', null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
