# Generated by Django 3.2.8 on 2026-04-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_column='full_name', max_length=200, null=True)),
                ('nombre_usuario', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('biografia', models.TextField(blank=True, db_column='bio', null=True)),
                ('url_avatar', models.TextField(blank=True, db_column='avatar_url', null=True)),
                ('telefono', models.CharField(blank=True, db_column='phone', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, db_column='address', null=True)),
                ('ciudad', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('pais', models.CharField(db_column='country', default='Colombia', max_length=100)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], db_column='role', default='client', max_length=20)),
                ('esta_activo', models.BooleanField(db_column='is_active', default=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
