# Generated by Django 3.2.8 on 2026-04-06 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='name', max_length=100)),
                ('enlace', models.SlugField(db_column='slug', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='description', null=True)),
                ('icono', models.CharField(blank=True, db_column='icon', max_length=50, null=True)),
                ('url_imagen', models.TextField(blank=True, db_column='image_url', null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.TextField(db_column='image_url')),
                ('texto_alt', models.CharField(blank=True, db_column='alt_text', max_length=200, null=True)),
                ('orden', models.IntegerField(db_column='sort_order', default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['orden'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='name', max_length=200)),
                ('enlace', models.SlugField(db_column='slug', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='description', null=True)),
                ('descripcion_corta', models.CharField(blank=True, db_column='short_description', max_length=500, null=True)),
                ('precio', models.DecimalField(db_column='price', decimal_places=2, default=0, max_digits=10)),
                ('existencias', models.IntegerField(db_column='stock', default=0)),
                ('marca', models.CharField(blank=True, db_column='brand', max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, db_column='model', max_length=100, null=True)),
                ('codigo_sku', models.CharField(blank=True, db_column='sku', max_length=100, null=True, unique=True)),
                ('especificaciones', models.JSONField(blank=True, db_column='specifications', default=dict)),
                ('url_imagen_principal', models.TextField(blank=True, db_column='main_image_url', null=True)),
                ('esta_activo', models.BooleanField(db_column='is_active', default=True)),
                ('es_destacado', models.BooleanField(db_column='is_featured', default=False)),
                ('conteo_vistas', models.IntegerField(db_column='views_count', default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('actualizado_el', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['-creado_el'],
                'managed': False,
            },
        ),
    ]
